final class TradeBotNameProvider {
    // MARK: - Properties
    var maxNamesCount: Int {
        tradingBotNames.count
    }
    
    // MARK: - State
    private let tradingBotNames = [
        "BotTradeMaster",
        "BotSuperTrade",
        "BotMarketPilot",
        "BotProfitHunter",
        "BotSmartTrader",
        "BotTradeRocket",
        "BotAlphaTrade",
        "BotCryptoMaster",
        "BotSignalPro",
        "BotTradeNinja",
        "BotMarketWizard",
        "BotProfitPilot",
        "BotAutoTrader",
        "BotTradeGenius",
        "BotBullRunner",
        "BotBearShield",
        "BotTradeStorm",
        "BotMarketSeeker",
        "BotFastProfit",
        "BotTradeEngine",
        "BotSmartSignal",
        "BotProfitMachine",
        "BotTradeLegend",
        "BotMarketMaster",
        "BotAlphaPilot",
        "BotTradeHunter",
        "BotSignalMaster",
        "BotCryptoPilot",
        "BotProfitWizard",
        "BotTradeFalcon",
        "BotMarketRocket",
        "BotAutoProfit",
        "BotTradeGuru",
        "BotSignalHunter",
        "BotAlphaTrader",
        "BotProfitStorm",
        "BotTradeWizard",
        "BotMarketNinja",
        "BotSmartProfit",
        "BotCryptoHunter",
        "BotTradePilot",
        "BotSignalRocket",
        "BotProfitLegend",
        "BotMarketFalcon",
        "BotTradeMachine",
        "BotAlphaSignal",
        "BotSmartTrade",
        "BotProfitNinja",
        "BotCryptoWizard",
        "BotTradeChampion",
        "BotTrendMaster",
        "BotMarketHunter",
        "BotSignalPilot",
        "BotTradeEagle",
        "BotProfitEngine",
        "BotAlphaRocket",
        "BotSmartPilot",
        "BotCryptoSignal",
        "BotTradeRanger",
        "BotMarketStorm",
        "BotProfitSeeker",
        "BotSignalWizard",
        "BotAutoSignal",
        "BotTradePhantom",
        "BotMarketGenius",
        "BotProfitRocket",
        "BotAlphaHunter",
        "BotSmartRocket",
        "BotCryptoTrader",
        "BotTradeVortex",
        "BotSignalFalcon",
        "BotMarketLegend",
        "BotProfitMaster",
        "BotAlphaWizard",
        "BotSmartHunter",
        "BotCryptoRocket",
        "BotTradePhoenix",
        "BotMarketEngine",
        "BotSignalStorm",
        "BotProfitFalcon",
        "BotAlphaMachine",
        "BotSmartWizard",
        "BotCryptoNinja",
        "BotTradeTitan",
        "BotMarketSignal",
        "BotProfitTrader",
        "BotAlphaGenius",
        "BotSmartEngine",
        "BotCryptoFalcon",
        "BotTradeOracle",
        "BotMarketChampion",
        "BotSignalEngine",
        "BotProfitGuru",
        "BotAlphaStorm",
        "BotSmartFalcon",
        "BotCryptoLegend",
        "BotTradeNova",
        "BotMarketTrader",
        "BotSignalMachine",
        "BotProfitChampion",
        "BotAlphaFalcon",
        "BotSmartMachine",
        "BotCryptoStorm",
        "BotTradeVector",
        "BotMarketGuru",
        "BotSignalTrader",
        "BotProfitSignal",
        "BotAlphaChampion",
        "BotSmartLegend",
        "BotCryptoMachine",
        "BotTradePulse",
        "BotMarketVector",
        "BotSignalLegend",
        "BotProfitVector",
        "BotAlphaEngine",
        "BotSmartChampion",
        "BotCryptoGuru",
        "BotTradeBlazer",
        "BotMarketPulse",
        "BotSignalChampion",
        "BotProfitPulse",
        "BotAlphaVector",
        "BotSmartGuru",
        "BotCryptoChampion",
        "BotTradeZenith",
        "BotMarketBlazer",
        "BotSignalVector",
        "BotProfitBlazer",
        "BotAlphaPulse",
        "BotSmartVector",
        "BotCryptoPulse",
        "BotTradeApex",
        "BotMarketZenith",
        "BotSignalPulse",
        "BotProfitZenith",
        "BotAlphaBlazer",
        "BotSmartPulse",
        "BotCryptoVector",
        "BotTradePrime",
        "BotMarketApex",
        "BotSignalBlazer",
        "BotProfitApex",
        "BotAlphaZenith",
        "BotSmartBlazer",
        "BotCryptoApex",
        "BotTradeEdge",
        "BotMarketPrime",
        "BotSignalZenith",
        "BotProfitPrime",
        "BotAlphaApex",
        "BotSmartPrime"
    ]
    
    private var availableNames: [String] = []
    
    // MARK: - Lifecycle
    init() {
        self.availableNames = tradingBotNames.shuffled()
    }
    
    // MARK: - Public Methods
    func getRandomName() -> String? {
        guard !availableNames.isEmpty else { return nil }
        
        return availableNames.removeLast()
    }
    
    func reset() {
        availableNames = tradingBotNames.shuffled()
    }
}
